version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: repository-01
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: aBc_123456
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data